# Generated by Django 3.0.3 on 2020-08-29 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Telugu', 'Telugu'), ('Tamil', 'Tamil'), ('Kannada', 'Kannada'), ('Bollywood', 'Bollywood'), ('Hollywood', 'Hollywood')], max_length=15)),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='')),
                ('size', models.CharField(max_length=15)),
                ('resolution', models.CharField(max_length=15)),
                ('director', models.CharField(max_length=50)),
                ('cast', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=15)),
                ('movie_story', models.TextField()),
                ('download_link', models.CharField(max_length=256)),
                ('slug', models.SlugField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('movies', django.db.models.manager.Manager()),
            ],
        ),
    ]
